Polish dist
theochem/DiverseSelector pull request #137
Opened 2023-06-20 20:11 UTC by AWBroscius

Address post pull request task list todos in [Issue 125](https://github.com/theochem/DiverseSelector/issues/125)

2023-07-05 20:17 UTC, FarnazH requested changes

2023-07-05 20:17 UTC, FarnazH commented on DiverseSelector/distance.py
> +    dist = distance_matrix(x, x) + 100*np.eye(x.shape[0])
@AWBroscius, we talked about changing `100` to `np.inf`. Can you please fix this?

2023-07-05 20:17 UTC, FarnazH commented on DiverseSelector/distance.py
> +    print(f"these are the shortest indices:", short_idx)
Remove the print statement.

2023-07-05 20:17 UTC, FarnazH commented on DiverseSelector/distance.py
> +    for idx in range(0, len(short_idx)):
Better to use `for idx, min_d in enumerate(short_idx):` and change the body of for loop accordingly.

2023-07-06 05:57 UTC, FanwangM approved these changes

2023-07-09 04:11 UTC, FanwangM commented
The failing tests has been fixed by rebasing and I will address the styling in another PR soon.

2023-07-09 04:11 UTC, merged

2023-07-09 13:12 UTC, FarnazH commented
I leave a note here, as this PR is already merged. Before #125 can be closed:

- The `modified_tanimoto` still needs to be finalized by @FarnazH.
- The module name should be changed as it contains similarity measures, not distances.