Sim2dist
theochem/DiverseSelector pull request #139
Opened 2023-06-21 20:47 UTC by AWBroscius

2023-06-23 00:14 UTC, FarnazH requested changes
This functionality should be implemented in the `converter.py` module.

2023-06-30 01:02 UTC, FanwangM requested changes
This is a big improvement and I enjoy reading the codes a lot. Nice job!

Sorry for being so picky, but we all want to make the package nice and easy to read/maintain.

2023-07-04 14:37 UTC, AWBroscius commented on DiverseSelector/converter.py
> +import numpy as np
I am not sure what you want changed here. Importing `numpy` automatically imports `ndarray`.

2023-07-04 16:21 UTC, AWBroscius commented
Hi @FanwangM I just pushed another commit that addresses most of your comments. Thank you for the advice. Feel free to look it over again when you have the chance.

2023-07-26 22:21 UTC, FarnazH commented on DiverseSelector/converter.py
> +import numpy as np
The `np.ndarray` is used, so there is no need to import `ndarray`.

2023-08-05 04:58 UTC, FanwangM commented
I am good with current PR. Do you have any other comments for this PR?  @FarnazH

2023-09-08 13:15 UTC, FarnazH approved these changes
Thanks, @AWBroscius for your contribution. The code looks good to me overall, but I will most likely add some changes later to make it more consistent with the rest of the code.

2023-09-08 13:16 UTC, merged