Proposed changes to API
theochem/DiverseSelector pull request #27
Opened 2022-02-09 03:49 UTC by RichRick1

1. made load_data, saveoutput and _normalize_desc method the concrete ones, because they shouldn't depend on the cluster or diversity method of selection
2. add __init__ method to a SelectionBase abstract class, because there are properties that can be the same for both Cluster and Dissimilarity selectors
3. rewrite DessimilaritySelector class based on the changes of the parent class (even thought it's an abstract class)

2022-02-09 14:53 UTC, fwmeng88 requested changes
Thanks for the contribution! There are just some minor changes required or something that I am not very clear of.

2022-02-09 15:46 UTC, RichRick1 commented on DiverseSelector/base.py
> +        # in the same way
You are right. Idea here is if we gonna use the same structure of the data and the same method for calculating diversity of the subset, we can use one method for calculating the subset diversity and code it here _explicitly_

2022-02-09 15:48 UTC, RichRick1 commented on DiverseSelector/base.py
> +        # in the same way
The same idea. As long as we are having all data in the same format and all methods for calculating diversity are the same at both DiverseSelector and ClusterSelector, we can make this method _concrete_ and implement right in here

2022-02-09 15:48 UTC, RichRick1 commented on DiverseSelector/dissimilarity_based.py
>          pass
Sure! Will do

2022-02-09 19:31 UTC, RichRick1 commented
Implement load_data as moving get_features

2022-02-10 17:49 UTC, RichRick1 commented
@fwmeng88 add implementation of MinMax algorithm and fixed `load_data` function. 
Also, add visualization for MinMax algorithm, however faced several issues with relative imports, so in visualization only code with the algorithm
Please, let me know what do you think about it

2022-02-10 18:42 UTC, fwmeng88 requested changes
Thanks for the nice improvement! Only one minor change for the imports. @RichRick1

2022-02-10 19:21 UTC, RichRick1 commented on DiverseSelector/base.py
> +from utils import *
Thanks! It's been fixed

2022-02-10 23:31 UTC, fwmeng88 approved these changes
Thanks for the nice contribution!!

2022-02-10 23:32 UTC, merged